"""Initial

Revision ID: 41b80b8234f1
Revises: 
Create Date: 2022-10-26 13:49:46.230778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b80b8234f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('accession', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('accession')
    )
    op.create_table('samples',
    sa.Column('accession', sa.String(length=20), nullable=False),
    sa.Column('project_acession', sa.String(length=20), nullable=True),
    sa.Column('instrument_platform', sa.String(length=30), nullable=False),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('fastq_md5', sa.String(length=255), nullable=True),
    sa.Column('fastq_ftp', sa.String(length=255), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('json_metadata', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UNPROCESSED', 'DOWNLOADED', 'ERROR', name='samplestatus'), server_default='UNPROCESSED', nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_acession'], ['projects.accession'], ),
    sa.PrimaryKeyConstraint('accession')
    )
    op.execute(
        """
        create view sample_view as
        select accession 
        from samples 
        where status = 'available'
        order by collection_date desc
        fetch first 10 rows only
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("drop view sample_view")
    op.drop_table('samples')
    op.drop_table('projects')
    # ### end Alembic commands ###
