"""initial

Revision ID: ce2b8c6b5676
Revises: 
Create Date: 2022-10-19 15:17:06.642145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2b8c6b5676'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('accession', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('accession')
    )
    op.create_table('samples',
    sa.Column('accession', sa.String(length=20), nullable=False),
    sa.Column('project_acession', sa.String(length=20), nullable=True),
    sa.Column('instrument_platform', sa.String(length=30), nullable=False),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('fastq_md5', sa.String(length=255), nullable=True),
    sa.Column('fastq_ftp', sa.String(length=255), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('json_metadata', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('available', 'downloaded', 'error', name='sample_status'), server_default='available', nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_acession'], ['projects.accession'], ),
    sa.PrimaryKeyConstraint('accession')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samples')
    op.drop_table('projects')
    # ### end Alembic commands ###
